### ISSUE TITLE
Problema ao clicar no fale conosco

### ISSUE THREAD

**Issue by 0bvim** [JessicaNathany/cafedebug-backend.api#12]
Quando estou no `https://cafedebug.com.br/` e clico no Fale conosco ele vai para o final da pagina onde tem a opcao de 'falar conosco'.
![image](https://github.com/JessicaNathany/cafedebug-backend.api/assets/130008311/7ab26022-2070-4c06-9150-812b272b6e0d)

Porem se eu estou no `https://cafedebug.com.br/episodios` ou no `https://cafedebug.com.br/debugers`, quando eu clico no fale conosco, ele nao faz nada, como nao tem a opcao embaixo ele simplesmente nao acontece nada.

![image](https://github.com/JessicaNathany/cafedebug-backend.api/assets/130008311/8233a1a4-22aa-4b39-afe5-09e4b1f44f56)

dia 05/06/2024 as 00:47

**Comment by JessicaNathany** [comment]
opa tudo bom? Sim está quebrado :/
o site atual está com alguns bugs, inclusive para cadastrar episódios estou fazendo insert diretamente no banco, mas o projeto não é este. O site atual do café não é este projeto, esse é o novo site que estou desenvolvendo dividindo o backend do frontend, ai ja estou fazendo com essas melhorias

**Comment by 0bvim** [comment]
> opa tudo bom? Sim está quebrado :/ o site atual está com alguns bugs, inclusive para cadastrar episódios estou fazendo insert diretamente no banco, mas o projeto não é este. O site atual do café não é este projeto, esse é o novo site que estou desenvolvendo dividindo o backend do frontend, ai ja estou fazendo com essas melhorias

Desculpa, eu poderia so ter lido o readme e tirado essa conclusao e nao feito essa issue! Boa sorte no desenvolvimento da API e se a contribuicao for open, posso tentar ajudar, nao sei muita coisa de C#, mas estou aprendendo sobre API e implementei alguns end points usando ktor(kotlin) em um projeto voluntario!
